### ISSUE TITLE
Documentation for Alpha

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#65] opened 2016-04-29 21:56 UTC
Documentation should be for an Apigee org admin deploying a node.js app to Apigee-K8S cluster. Assume that user knows her admin credentials and has a zip file of node.js app
- API to upload source zip
- API to deploy the app
- Instruction on how to create a proxy on Edge

**Comment by tnine** [comment] 2016-06-01 17:27
Duplicate of #78

**Closed as completed by tnine** 2016-06-01 17:27 UTC
