### ISSUE TITLE
service that updates calico rule based on POD events

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#71] opened 2016-05-04 17:40 UTC

**Comment by prabhatjha** [comment] 2016-05-10 20:15
@jbowen93 We think this is for you. What other info you need?

**Comment by prabhatjha** [comment] 2016-05-23 17:37
Assigning to @mpnally to further clarify this task.

**Comment by mpnally** [comment] 2016-06-01 19:30
Duplicate of #85 which describes the issue more clearly

**Closed as completed by mpnally** 2016-06-01 19:30 UTC
